euro_price= 11
taux_horaire= 8
operations = operations_times = {
    "Coupe Gaine": 30,
    "Coupe Cable": 45,
    "Coupe Cable MULTI FBR DUAL": 40,
    "Marquage Cable": 30,
    "Dégainage": 45,
    "Préparation blindage": 180,
    "Recoupe": 30,
    "Dénudage cable": 10,
    "Coupe fil simple": 30,
    "Lovage": 30,
    "Marquage": 30,
    "Dénudage": 10,
    "Pose joint": 20,
    "Sertissage": 30,
    "Traitement bout fil de puissance": 120,
    "Epissurage": 150,
    "Coupe manchon": 20,
    "Pose manchon": 10,
    "Retreint": 30,
    "Routage cheminement": 15,
    "Enfilage gaine": 60,
    "Insertion connecteur": 20,
    "Soudage": 40,
    "Pose collier": 20,
    "Assemblage connecteur": 40,
    "Impression etiquette": 15,
    "Pose etiquette": 15,
    "Test electrique": 10,
    "Emballage": 2,
}